language: ruby
rvm:
  - 2.6.6
  - truffleruby
  - truffleruby-head
matrix:
  include:
    - rvm: 2.5.1
      os: osx
      osx_image: xcode9.4
dist: trusty
sudo: true
before_install:
  - gem update --system
  - gem install bundler -v 1.16.2
cache: bundler
